name: yumme
description: A new Flutter project.

publish_to: 'none' # Prevents publishing to pub.dev

version: 3.5.3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  

  # Core & UI
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  animated_text_kit: ^4.2.2
  animated_emoji: ^3.1.0
  font_awesome_flutter: ^10.8.0
  flutter_fortune_wheel: ^1.1.2

  # Image & Media
  cached_network_image: ^3.2.3
  image_picker: ^1.1.2

  # HTTP & APIs
  http: ^1.2.1
  googleapis_auth: ^1.3.0
  url_launcher: ^6.2.5
  flutter_linkify: ^6.0.0
  intl: ^0.20.1 # or update to a newer version (e.g., ^0.17.0)

  # Chatbot & Messaging
  flutter_chat_ui: ^1.6.0


  # Maps & Location
  location: ^8.0.0
  latlong2: ^0.9.1
  syncfusion_flutter_maps: ^29.1.40
  flutter_map: 7.0.2
  flutter_map_marker_cluster: ^1.4.0
  geolocator: ^14.0.0
  


  # Authentication
  google_sign_in: ^6.2.2

  # Storage
  sqflite: ^2.4.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  path: ^1.9.1
  pdf: ^3.11.3
  printing: ^5.14.2
  fl_chart: ^1.0.0
  
  # Android lifecycle plugin (important for background/location plugins)
  flutter_plugin_android_lifecycle: ^2.0.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/yumme.png
    - assets/data/top_rated_restaurants_with_osm.json